name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t flask-app .
          docker tag flask-app achin16/flask-app
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: achin16/flask-app:latest