name: Kubernetes Web
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - name: Login to Docker Hub
        uses: docker/login-action@bc135a1993a1d0db3e9debefa0cfcb70443cc94c
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t flask-app .
          docker tag flask-app achin16/flask-app
      - name: Push
        uses: docker/build-push-action@4eb68bb2ac65309f0a26ed9abf968f9ea36bd29f
        with:
          push: true
          tags: achin16/flask-app:latest